### ISSUE TITLE
Questions about the combination of detection output categories and Captum

### ISSUE THREAD

**Issue by LY54** [reedless/captum-detectron2#2]
It's a good work.

When there are multiple targets in the input image and multiple prediction box information in the network prediction output, how can we classify the well-founded summation category score for Captum interpretation?
I hope you can help me solve this confusion , and thank you very much.

**Comment by reedless** [comment]
Hi @LY54, thanks for the question! This repo is still very much a work in progress, and my approach was to first perform one forward pass to get all the unique classes detected in the sample image, then iterate through the classes, setting each as the target class for captum's algorithms https://github.com/reedless/captum-detectron2/blob/main/main.py#L99.

You can see more of my discussion with the captum team here: https://github.com/pytorch/captum/issues/901

**Comment by LY54** [comment]
Ok, thank you very much for your answer!

**Comment by LY54** [comment]
Every time you run the model, the results of the integral gradient are inconsistent. Have you ever encountered this situation?
I tested the single-class detection task on YOLO. The prediction head of the network outputs the multidimensional tensor NxHxWx3x(5+Class) through 1x1 convolution, and the detection results are filtered out through the detector NMS.
In the way of packaging function, I used global average pooling to obtain 3X (5+Class) after 1x1 convolution, combined with sigmoid function, and then selected the index of the maximum category score box as the final Captum interpretation. Do you think there is a problem with this way?

**Comment by LY54** [comment]
Is it normal for the Integrated Gradients (IG) output to be inconsistent each time the model is run for prediction?  Have you ever come across such a situation ?

**Comment by reedless** [comment]
Hi @LY54, so far I have not encountered such an issue with Captum IG, but some things you can check are the input, baseline, and target class, followed by python environment and hardware. You can also try setting the random seeds and other fixes mentioned here:
https://pytorch.org/docs/stable/notes/randomness.html

**Comment by LY54** [comment]
Thank you very much for your kind help, I solved this problem.
